# Generated by Django 3.0.2 on 2020-03-09 23:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_auto_20200310_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='id',
        ),
        migrations.AddField(
            model_name='basket',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
