# Generated by Django 3.0.2 on 2020-03-10 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200310_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vendor_code',
            field=models.CharField(default='CX1583800985.868395H01', max_length=100, verbose_name='Артикул'),
        ),
    ]
